### ISSUE TITLE
Misleading y-axis

### ISSUE THREAD

**Issue by kodonnell** [thekvs/cpp-serializers#13]
Quick comment that your images make it appear that e.g. protobuf'd objects are 10x smaller than cap'n proto ones, which is untrue. This is because the y-axis doesn't start at 'zero' (which is considered bad practice for this reason).

**Comment by Kentzo** [comment]
I guess it should how much % it's better than the worst case somewhere near the graph.

**Comment by Kentzo** [comment]
Probably a related problem is that color is not preserved between tests.

**Comment by kodonnell** [comment]
> I guess it should how much % it's better than the worst case somewhere near the graph.

This could still have the same problem. The point is you want the height of the bar to represent the size of the value - and hence the axis must start at (in this case) y = 0.

**Comment by Kentzo** [comment]
With y = 0 the graph will be unnecessarily huge and won't have any visible difference.

**Comment by kodonnell** [comment]
> With y = 0 the graph will be unnecessarily huge and won't have any visible difference.

That's the point - if you can't see any visible difference, then it means there's no material difference. However, there *will* be a visible difference in this case e.g. yas is twice as fast as cereal, so the yas bar will be twice as small/large (whereas now there's more like +-20% difference).

> Perhaps instead of absolute numbers it should show percentage

The graph would look exactly the same, just the labels changed. As above, yas would still be twice as small/large as cereal.

**Comment by Kentzo** [comment]
Hmm, why would it look exactly the same? Percentage would accurately show how much compression of A is better than of B.

**Comment by kodonnell** [comment]
Say 10 seconds is worst case and hence 100%. That will be a full height bar. Say something takes 5s, or 50%  - whether the axis is 0 - 10s or 0 - 100%, it'll still show a half-height bar.

**Comment by Kentzo** [comment]
In that case half-height bar is what I as a reader would expect and it would show that something that takes 5s is twice better than something else that takes 10s.

**Comment by kodonnell** [comment]
> half-height bar is what I as a reader would expect and it would show that something that takes 5s is twice better than something else that takes 10s

Correct - that's why the y-axis needs to be 'zeroed'.

**Comment by Kentzo** [comment]
But that's not enough, for graphics to be useful measure point also needs to be changed.

**Comment by kodonnell** [comment]
I'm not sure what you mean.

**Comment by nbelakovski** [comment]
Seems like this thread has died, but I came here to say the same thing as @kodonnell, the size graph needs to start at 0. As it is it is misleading. Glancing at it makes it seem that capnproto takes ~10x more space than yas-compact, but going through the numbers it actually is only 33% bigger. Whether you do percent or size it doesn't matter, please pick whichever one you like better, but the y-axis must start at 0. The graph will not look overly huge, it will just show that there's not as much difference between these protocols in terms of size (which is the truth).

**Comment by nbelakovski** [comment]
Until the graph is fixed, there should be a disclaimer, I added one in #22
